spring:
  datasource:
    url: jdbc:mysql://mysql:3306/myflp
    username: root
    password: mVPLC17OL1YDurXVJ9cGAF
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    contexts: prod

  app:
    email:
      url: https://myflp.pl