spring:
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/master.xml

  profiles:
    active: dev

  app:
    email:
      login: ${EMAIL_USERNAME}
      password: ${EMAIL_KEY}

server:
  servlet:
    session:
      cookie:
        max-age: 7776000
      timeout: 2592000


